[setup]
repository = "https://raw.githubusercontent.com/antonw51/better-disc-mojis/main/res"

[emojis]
angry = { position = "10,2", emoji = "ğŸ˜ ", discord_id = "13d0b034e3b6a99d0d8c" }
anguished = { position = "42,2", emoji = "ğŸ˜§", discord_id = "b1e7c5e71d5e6b852c16" }
astonished = { position = "2,3", emoji = "ğŸ˜²", discord_id = "c57f1b6f6049760e301f" }
cold_face = { position = "16,2", emoji = "ğŸ¥¶", discord_id = "becafe5ab638053621b8" }
confounded = { position = "3,2", emoji = "ğŸ˜–", discord_id = "578a868786e07850a386" }
confused = { position = "41,1", emoji = "ğŸ˜•", discord_id = "578a868786e07850a386" }
cowboy = { position = "19,3", emoji = "ğŸ¤ ", discord_id = "d2835007fc134e3eea41" }
cry = { position = "7,2", emoji = "ğŸ˜¢", discord_id = "f5caf622bd0291b9f523" }
disappointed = { position = "38,1", emoji = "ğŸ˜", discord_id = "20d77e7234cb9860b8eb" }
disguised_face = { position = "33,1", emoji = "ğŸ¥¸", discord_id = "8dc4411bd6c69c5ad581" }
dizzy_face = { position = "8,3", emoji = "ğŸ˜µ", discord_id = "2c42190bd41ff6dd2ecd" }
dotted_line_face = { position = "33,2", emoji = "ğŸ«¥", discord_id = "683517ff39118a16517d" }
expressionless = { position = "36,2", emoji = "ğŸ˜‘", discord_id = "dcf09a09390c256a9f07" }
face_vomiting = { position = "13,3", emoji = "ğŸ¤®", discord_id = "524f62229e637aad3318" }
face_with_diagonal_mouth = { position = "35,2", emoji = "ğŸ«¤", discord_id = "a13cdf0003538ef352ea" }
face_with_monocle = { position = "30,1", emoji = "ğŸ§", discord_id = "356a2040e471bc75bd14" }
face_with_raised_eyebrow = { position = "29,1", emoji = "ğŸ¤¨", discord_id = "e6985d34ecca5371ec56" }
face_with_spiral_eyes = { position = "8,3", emoji = "ğŸ˜µâ€ğŸ’«", discord_id = "a31031c4662e69d42c56" }
frowning = { position = "42,2", emoji = "ğŸ˜¦", discord_id = "2dbaa2a43fb9de17d663" }
frowning2 = { position = "1,2", emoji = "â˜¹ï¸", discord_id = "9c3657727e0b3e3b999d" }
grimacing = { position = "37,2", emoji = "ğŸ˜¬", discord_id = "7cba7efd329d2fdd69fb" }
grinning = { position = "2,1", emoji = "ğŸ˜€", discord_id = "6cec8716b466d02f9703" }
head_bandage = { position = "17,3", emoji = "ğŸ¤•", discord_id = "139cdb078c7ed4f3560f" }
hot_face = { position = "15,2", emoji = "ğŸ¥µ", discord_id = "1424638f245cca2f0126" }
imp = { position = "19,3", emoji = "ğŸ‘¿", discord_id = "d866d256c735768a71a1" }
innocent = { position = "13,1", emoji = "ğŸ˜‡", discord_id = "b25cb434a33135add40b" }
joy = { position = "8,1", emoji = "ğŸ˜‚", discord_id = "2cc23a476525f31b100e" }
kissing = { position = "21,1", emoji = "ğŸ˜—", discord_id = "96b3b8d8e25e74f4d89c" }
kissing_heart = { position = "20,1", emoji = "ğŸ˜˜", discord_id = "acd7bc9b099abbb2d8ba" }
kissing_smiling_eyes = { position = "22,1", emoji = "ğŸ˜™", discord_id = "5288cb65ebb6a49b77e4" }
laughing = { position = "5,1", emoji = "ğŸ˜†", discord_id = "b68b76379e4f6fd8f13b" }
mask = { position = "15,3", emoji = "ğŸ˜·", discord_id = "f013c5795cd830fc52af" }
melting_face = { position = "30,2", emoji = "ğŸ« ", discord_id = "5ba2d0026109e7402c0e" }
money_mouth = { position = "18,3", emoji = "ğŸ¤‘", discord_id = "6c12fc84045ebd701099" }
nauseated_face = { position = "12,3", emoji = "ğŸ¤¢", discord_id = "3901b383e4688d6a9732" }
nerd = { position = "31,1", emoji = "ğŸ¤“", discord_id = "cccf954be87af0949c0b" }
neutral_face = { position = "34,2", emoji = "ğŸ˜", discord_id = "a8f5c8f4f00af7c67c68" }
no_mouth = { position = "32,2", emoji = "ğŸ˜¶", discord_id = "505b334606cbd28567cf" }
open_mouth = { position = "1,3", emoji = "ğŸ˜®", discord_id = "65ef7af8aca0d7a9e498" }
partying_face = { position = "35,1", emoji = "ğŸ¥³", discord_id = "cb5c9474e09650bc9f55" }
pensive = { position = "40,1", emoji = "ğŸ˜”", discord_id = "3657345e3960d3231197" }
persevere = { position = "2,2", emoji = "ğŸ˜£", discord_id = "0fd3df9b1aad95032a97" }
rage = { position = "11,2", emoji = "ğŸ˜¡", discord_id = "cfb7b0eb6372a33d6d31" }
relieved = { position = "17,1", emoji = "ğŸ˜Œ", discord_id = "fc505bb0a9ea12951208" }
rofl = { position = "9,1", emoji = "ğŸ¤£", discord_id = "93b4a3b6b97c6f6fe355" }
saluting_face = { position = "27,2", emoji = "ğŸ«¡", discord_id = "866f368304f01ed3b6cd" }
scream = { position = "18,2", emoji = "ğŸ˜±", discord_id = "e8d45dcac02e5581da2d" }
skull = { position = "26,2", emoji = "ğŸ’€", discord_id = "6578cc0c4f5cf6888655" }
sleeping = { position = "4,3", emoji = "ğŸ˜´", discord_id = "622cad2bf1042da86349" }
slight_frown = { position = "43,1", emoji = "ğŸ™", discord_id = "fe7de01926a65fc90c64" }
slight_smile = { position = "14,1", emoji = "ğŸ™‚", discord_id = "692c34d74838a4947011" }
smile = { position = "3,1", emoji = "ğŸ˜„", discord_id = "7f80202d4394f6368029" }
smiley = { position = "2,1", emoji = "ğŸ˜ƒ", discord_id = "bb478174944db83aac1e" }
smiling_face_with_3_hearts = { position = "19,1", emoji = "ğŸ¥°", discord_id = "d23e1a25d1d460aad885" }
smiling_face_with_tear = { position = "10,1", emoji = "ğŸ¥²", discord_id = "1e7e01be491dd78ec7ac" }
smiling_imp = { position = "20,3", emoji = "ğŸ˜…", discord_id = "21c05c04370d98dc1b76" }
smirk = { position = "37,1", emoji = "ğŸ˜", discord_id = "ca08e7b64885cdea21fe" }
sob = { position = "8,2", emoji = "ğŸ˜­", discord_id = "76800d59a30c256703d3" }
stuck_out_tongue = { position = "25,1", emoji = "ğŸ˜›", discord_id = "13a97bb425ad8bb2dce7" }
stuck_out_tongue_closed_eyes = { position = "26,1", emoji = "ğŸ˜", discord_id = "3a7ab9284e9a1ab51805" }
stuck_out_tongue_winking_eye = { position = "27,1", emoji = "ğŸ˜œ", discord_id = "5fdd196412748b172336" }
sunglasses = { position = "32,1", emoji = "ğŸ˜", discord_id = "6fedffddf7adb4b5f902" }
sweat_smile = { position = "7,1", emoji = "ğŸ˜…", discord_id = "21c05c04370d98dc1b76" }
upside_down = { position = "15,1", emoji = "ğŸ™ƒ", discord_id = "6e420b8ead5536a29e6e" }
weary = { position = "5,2", emoji = "ğŸ˜©", discord_id = "790db73c4710e67ce248" }
wink = { position = "16,1", emoji = "ğŸ˜‰", discord_id = "09d62575fb7067417846" }
woozy_face = { position = "11,3", emoji = "ğŸ¥´", discord_id = "612d2bc5d16ae7d2a679" }
worried = { position = "41,1", emoji = "ğŸ˜Ÿ", discord_id = "50d6842ad86241b2f4bd" }
yum = { position = "24,1", emoji = "ğŸ˜‹", discord_id = "4484b267bdc98a0b28e8" }
zany_face = { position = "28,1", emoji = "ğŸ¤ª", discord_id = "5fdd196412748b172336" }
